//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoomAvailability
    {
        public int Id { get; set; }
        public System.DateTime TimeSlotStart { get; set; }
        public System.DateTime TimeSlotEnd { get; set; }
        public int RoomId { get; set; }
        public bool IsReserved { get; set; }
    
        public virtual HotelRoom HotelRoom { get; set; }
    }
}
